# discord 配置
DISCORD_USER_TOKEN: MTA5MzAzMDQ5NjU0MTM1NjA2Mg.GgRBkG.t8iucteOiHTuljM3CWpEnJVDZUbMI9GKdFr6hU
DISCORD_BOT_TOKEN: MTEwMjIzOTcxNjg0MzE5NjUwOA.GKbkZe.PbPGnfhh0LEH3wAhCg-fDAO6mBo8STHYh6Xm1A
DISCORD_SERVER_ID: 1101834752857751615
DISCORD_CHANNEL_ID: 1101834753650466839
CB_URL: http://localhost:8099/image